#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jun 22 22:53:00 2019

@author: fabi
"""

# Packages
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
plt.style.use('seaborn-colorblind')

# Loading file
file = pd.read_csv('AfricanNamesDatabase.csv')

# Data wrangling
file = file.replace(' ', np.nan)

file.Sexage = file.Sexage.replace(np.nan, 'unknown')

file.Age = pd.to_numeric(file.Age, downcast='float')
file.Age = file.Age.fillna(file.Age.mean())

file['Height (in)'] = pd.to_numeric(file['Height (in)'], downcast='float')
file['Height (in)'] = file['Height (in)'].fillna(file['Height (in)'].mean())

file['Ship name'] = file['Ship name'].replace(np.nan, 'unknown')

file.Embarkation = file.Embarkation.replace(np.nan, 'unknown')

file['Country of Origin'] = file['Country of Origin'].replace(
        np.nan, 'unknown')

for col in file.columns:
    if file[col].dtype == np.object:
        file[col] = file[col].astype('category') 
        
# Analyzing data
file.head()        
file.info()
file.describe()
file.columns 

# Plots
# Disembarkation

disemb0 = file.Disembarkation.value_counts()
disemb0

disemb1 = pd.Series(disemb0[:2])
disemb2 = {'Bahamas, Jamaica e St. Helena': sum(disemb0[2:])}
disemb2 = pd.Series(disemb2, index=['Bahamas, Jamaica e St. Helena'])
disemb = pd.concat((disemb2, disemb1))
disemb

disemb_d = dict(disemb.sort_values(ascending=False))
disemb_dkeys, disemb_dvalues = zip(*disemb_d.items())

fig, ax = plt.subplots()
ax.pie(disemb_dvalues, autopct='%1.1f%%')
fig.legend(disemb_dkeys, loc=8)
plt.show()

print(disemb0)        

# Embarkations
emb0 = file.Embarkation.value_counts()
emb0.shape
emb0


emb1 = pd.Series(emb0[:5])
emb2 = {'others': sum(emb0[5:])}
emb2 = pd.Series(emb2, index=['others'])
emb = pd.concat((emb2, emb1))

emb_d = dict(emb.sort_values())
emb_dkeys, emb_dvalues = zip(*emb_d.items())

fig, ax = plt.subplots()
ax.pie(emb_dvalues, labels=emb_dkeys, autopct='%1.1f%%')

plt.show()   

print(emb)

# Frequency of disembarkations 
arrival = pd.DataFrame(file.Arrival.value_counts()).reset_index(
        ).sort_values(by='index')
arrival = arrival.rename(columns={'index': 'Year', 'Arrival': 
    'Rescued people'})
    
fig, ax = plt.subplots()    
ax.scatter(x='Year', y='Rescued people', data=arrival, marker='+')
ax.set_xlabel('Year')

plt.show()

# Origin
origin0a = file['Country of Origin'].value_counts()
origin0a.shape

origin1a = pd.Series(origin0a[:2])
origin2a = {'others': sum(origin0a[2:])}
origin2a = pd.Series(origin2a, index=['others'])
origina = pd.concat((origin2a, origin1a))

origina_d = dict(origina.sort_values())
origina_dkeys, origina_dvalues = zip(*origina_d.items())

fig, ax = plt.subplots()
ax.pie(origina_dvalues, labels=origina_dkeys, autopct='%1.1f%%')
plt.show()

print(origin0a.head(11))

origin0b = origin0a.iloc[1:]
origin0b.shape

origin1b = pd.Series(origin0b[:5])
origin2b = {'others': sum(origin0b[5:])}
origin2b = pd.Series(origin2b, index=['others'])
originb = pd.concat((origin2b, origin1b))

originb_d = dict(originb.sort_values(ascending=False))
originb_dkeys, originb_dvalues = zip(*originb_d.items())

fig, ax = plt.subplots()
ax.pie(originb_dvalues, autopct='%1.1f%%')
fig.legend(originb_dkeys, loc=4)
plt.show()

print(originb)

# Gênero
sexage = file.Sexage.value_counts()
sexage_d = dict(sexage)
sexage_dkeys, sexage_dvalues = zip(*sexage_d.items())

fig, ax = plt.subplots()
ax.pie(sexage_dvalues, autopct='%1.1f%%')
fig.legend(sexage_dkeys, loc=4)
plt.show()

print(sexage)

# Age  
age = file.Age
fig, ax = plt.subplots()    
ax.hist(age, log=True)
ax.set_xlabel('age')
plt.show()

age.describe()

# Ship name
ship0 = file['Ship name'].value_counts()
ship0.shape

ship1 = pd.Series(ship0[:1])
ship2 = {'others': sum(ship0[1:])}
ship2 = pd.Series(ship2, index=['others'])
ship = pd.concat((ship2, ship1))

ship_d = dict(ship.sort_values())
ship_dkeys, ship_dvalues = zip(*ship_d.items())

fig, ax = plt.subplots()
ax.pie(ship_dvalues, labels=ship_dkeys, autopct='%1.1f%%')
plt.show()

print(ship0.head())

shipb = ship0.head(10)
shipb_d = dict(shipb.sort_values())
shipb_dkeys, shipb_dvalues = zip(*shipb_d.items())

shipb = ship0.head(10)
shipb_d = dict(shipb.sort_values())
shipb_dkeys, shipb_dvalues = zip(*shipb_d.items())

fig, ax = plt.subplots()
ax.pie(shipb_dvalues, labels=shipb_dkeys, autopct='%1.1f%%', startangle=90)
plt.show()

print(shipb)

print('The 30 least occupied ships:')
print(ship0[-30:])

# ship with my name =( 
fabiana = file[file['Ship name'] == 'Fabiana']
fabiana.shape
fabiana.Embarkation.value_counts().head()
fabiana.Disembarkation.value_counts()
fabiana.Arrival.value_counts()

# Origin disembarked in Freetown
disemb_ft = file[file.Disembarkation == 'Freetown']
originfta0 = disemb_ft['Country of Origin'].value_counts()
originfta0.shape

originfta1 = pd.Series(originfta0[:1])
originfta2 = {'others': sum(originfta0[1:])}
originfta2 = pd.Series(originfta2, index=['others'])
originfta = pd.concat((originfta2, originfta1))

originfta_d = dict(originfta.sort_values())
originfta_d = {x:y for x, y in originfta_d.items() if y != 0} 
originfta_dkeys, originfta_dvalues = zip(*originfta_d.items())

fig, ax = plt.subplots()
ax.pie(originfta_dvalues, labels=originfta_dkeys, autopct='%1.1f%%')
plt.show()

print(originfta)

originftb0 = originfta0.iloc[1:]
originftb0.shape

originftb1 = pd.Series(originftb0[:3])
originftb2 = {'others': sum(originftb0[3:])}
originftb2 = pd.Series(originftb2, index=['others'])
originftb = pd.concat((originftb2, originftb1))

originftb_d = dict(originftb)
originftb_d = {x:y for x, y in originftb_d.items() if y != 0} 
originftb_dkeys, originftb_dvalues = zip(*originftb_d.items())

fig, ax = plt.subplots()
ax.pie(originftb_dvalues, autopct='%1.1f%%', counterclock=False)
fig.legend(originftb_dkeys, loc=4)
plt.show()

print(originftb)

# Gênero e idade
sexage_ft = disemb_ft.Sexage.value_counts()
sexageft_d = dict(sexage_ft)
sexageft_dkeys, sexageft_dvalues = zip(*sexageft_d.items())

fig, ax = plt.subplots()
ax.pie(sexageft_dvalues, autopct='%1.1f%%')
fig.legend(sexageft_dkeys, loc=4)
plt.show()

print(sexage_ft)

#Faixa etária
age_ft = disemb_ft.Age
fig, ax = plt.subplots()    
ax.hist(age_ft, log=True)
ax.set_xlabel('age')
plt.show()

age_ft.describe()

# Frequency of disembarkations at Freetown
arrivalft = pd.DataFrame(disemb_ft.Arrival.value_counts()).reset_index(
        ).sort_values(by='index')
arrivalft = arrivalft.rename(columns={'index': 'Year', 'Arrival': 
    'Rescued people'})
    
fig, ax = plt.subplots()  
ax.scatter(x='Year', y='Rescued people', data=arrivalft)  
ax.scatter(x='Year', y='Rescued people', data=arrival, marker='+', 
           c='#D55E00')
ax.set_xlabel('Years')
ax.legend(labels=['Freetown', 'total'])
plt.show()

# Embarkations to Freetown
embft0 = disemb_ft['Embarkation'].value_counts()
embft0.shape

embft1 = pd.Series(embft0[:7])
embft2 = {'others': sum(embft0[7:])}
embft2 = pd.Series(embft2, index=['others'])
embft = pd.concat((embft2, embft1))

embft_d = dict(embft.sort_values())
embft_dkeys, embft_dvalues = zip(*embft_d.items())

fig, ax = plt.subplots()
ax.pie(embft_dvalues, labels=embft_dkeys, autopct='%1.1f%%', 
       counterclock=False)
plt.show()

print(embft)

# Origin disembarked in Havana
disemb_hv = file[file.Disembarkation == 'Havana']
originhv0 = disemb_hv['Country of Origin'].value_counts()
originhv0.shape

originhv1 = pd.Series(originhv0[:6])
originhv2 = {'others': sum(originhv0[6:])}
originhv2 = pd.Series(originhv2, index=['others'])
originhv = pd.concat((originhv2, originhv1))

originhv_d = dict(originhv.sort_values())
originhv_d = {x:y for x, y in originhv_d.items() if y != 0} 
originhv_dkeys, originhv_dvalues = zip(*originhv_d.items())

fig, ax = plt.subplots()
ax.pie(originhv_dvalues, labels=originhv_dkeys, autopct='%1.1f%%')
plt.show()

print(originhv)

#Gênero
sexage_hv = disemb_hv.Sexage.value_counts()
sexagehv_d = dict(sexage_hv)
sexagehv_dkeys, sexagehv_dvalues = zip(*sexagehv_d.items())

fig, ax = plt.subplots()
ax.pie(sexagehv_dvalues, autopct='%1.1f%%')
fig.legend(sexagehv_dkeys, loc=4)
plt.show()

print(sexage_hv)

#Idade
age_hv = disemb_hv.Age
fig, ax = plt.subplots()    
ax.hist(age_hv, log=True)
ax.set_xlabel('age')
plt.show()

age_hv.describe()


# Frequency of disembarkations at Havana
arrivalhv = pd.DataFrame(disemb_hv.Arrival.value_counts()).reset_index(
        ).sort_values(by='index')
arrivalhv = arrivalhv.rename(columns={'index': 'Year', 'Arrival': 
    'Rescued people'})
    
fig, ax = plt.subplots()  
ax.scatter(x='Year', y='Rescued people', data=arrivalhv)  
ax.scatter(x='Year', y='Rescued people', data=arrival, marker='+', 
           c='#D55E00')
ax.set_xlabel('Year')
ax.legend(labels=['Havana', 'total'])
plt.show()  

# Embarkations to Havana
embhv0 = disemb_hv['Embarkation'].value_counts()
embhv0.shape

embhv1 = pd.Series(embhv0[:7])
embhv2 = {'others': sum(embhv0[7:])}
embhv2 = pd.Series(embhv2, index=['others'])
embhv = pd.concat((embhv2, embhv1))

embhv_d = dict(embhv.sort_values())
embhv_dkeys, embhv_dvalues = zip(*embhv_d.items())

fig, ax = plt.subplots()
ax.pie(embhv_dvalues, labels=embhv_dkeys, autopct='%1.1f%%')
plt.show()
   
print(embhv)
    
# Origin disembarked in Bahamas unspecified
disemb_bh = file[file.Disembarkation == 'Bahamas (unspecified)']
originbh0 = disemb_bh['Country of Origin'].value_counts()
originbh0.shape

originbh1 = pd.Series(originbh0[:10])
originbh2 = {'others': sum(originbh0[10:])}
originbh2 = pd.Series(originbh2, index=['others'])
originbh = pd.concat((originbh2, originbh1))

originbh_d = dict(originbh)
originbh_d = {x:y for x, y in originbh_d.items() if y != 0} 
originbh_dkeys, originbh_dvalues = zip(*originbh_d.items())

fig, ax = plt.subplots()
ax.pie(originbh_dvalues, labels=originbh_dkeys, autopct='%1.1f%%')
plt.show()

print(originbh)

#Gender
sexage_bh = disemb_bh.Sexage.value_counts()
sexagebh_d = dict(sexage_bh)
sexagebh_dkeys, sexagebh_dvalues = zip(*sexagebh_d.items())

fig, ax = plt.subplots()
ax.pie(sexagebh_dvalues, autopct='%1.1f%%')
fig.legend(sexagebh_dkeys, loc=4)
plt.show()

print(sexage_bh)

# Age  
age_bh = disemb_bh.Age
fig, ax = plt.subplots()    
ax.hist(age_bh, log=True)
ax.set_xlabel('age')
plt.show()

age_bh.describe()

# Frequency of disembarkations at Bahamas unspecified
arrivalbh = pd.DataFrame(disemb_bh.Arrival.value_counts()).reset_index(
        ).sort_values(by='index')
arrivalbh = arrivalbh.rename(columns={'index': 'Year', 'Arrival': 
    'Rescued people'})
    
fig, ax = plt.subplots()  
ax.scatter(x='Year', y='Rescued people', data=arrivalbh)  
ax.scatter(x='Year', y='Rescued people', data=arrival, marker='+', 
           c='#D55E00')
ax.set_xlabel('Year')
ax.legend(labels=['Bahamas (unspecified)', 'total'])
plt.show()   

# Embarkations to Bahamas unspecified
embbh0 = disemb_bh['Embarkation'].value_counts()

embbh1 = pd.Series(embbh0[:7])
embbh2 = {'others': sum(embbh0[7:])}
embbh2 = pd.Series(embbh2, index=['others'])
embbh = pd.concat((embbh2, embbh1))

embbh_d = dict(embbh.sort_values())
embbh_d = {x:y for x, y in embbh_d.items() if y != 0} 
embbh_dkeys, embbh_dvalues = zip(*embbh_d.items())

fig, ax = plt.subplots()
ax.pie(embbh_dvalues, labels=embbh_dkeys, autopct='%1.1f%%', counterclock=False)
plt.show()
    
print(embbh)
    
# Origin disembarked in Kingston, Jamaica
disemb_jm = file[file.Disembarkation == 'Kingston, Jamaica']
originjm0 = disemb_jm['Country of Origin'].value_counts()
originjm0.shape

originjm1 = pd.Series(originjm0[:10])
originjm2 = {'others': sum(originjm0[10:])}
originjm2 = pd.Series(originjm2, index=['others'])
originjm = pd.concat((originjm2, originjm1)).sort_values(ascending=False)

originjm_d = dict(originjm)
originjm_d = {x:y for x, y in originjm_d.items() if y != 0}
originjm_dkeys, originjm_dvalues = zip(*originjm_d.items())

fig, ax = plt.subplots()
ax.pie(originjm_dvalues, labels=originjm_dkeys, autopct='%1.1f%%')
fig.savefig('origin_jm_pt.png', dpi=300)
plt.show()

print(originjm)

#Gênero
sexage_jm = disemb_jm.Sexage.value_counts()
sexagejm_d = dict(sexage_jm)
sexagejm_dkeys, sexagejm_dvalues = zip(*sexagejm_d.items())

fig, ax = plt.subplots()
ax.pie(sexagejm_dvalues, autopct='%1.1f%%')
fig.legend(sexagejm_dkeys, loc=4)
plt.show()

print(sexage_jm)

#Faixa etária
age_jm = disemb_jm.Age
fig, ax = plt.subplots()    
ax.hist(age_jm, log=True)
ax.set_xlabel('age')
plt.show()

age_jm.describe()

# Frequency of disembarkations at Kingston, Jamaica
arrivaljm = pd.DataFrame(disemb_jm.Arrival.value_counts()).reset_index(
        ).sort_values(by='index')
arrivaljm = arrivaljm.rename(columns={'index': 'Year', 'Arrival': 
    'Rescued people'})
    
fig, ax = plt.subplots()  
ax.scatter(x='Year', y='Rescued people', data=arrivaljm)  
ax.scatter(x='Year', y='Rescued people', data=arrival, marker='+', 
           c='#D55E00')
ax.set_xlabel('Year')
ax.legend(labels=['Kingston, Jamaica', 'total'])
plt.show() 

# Embarkations to Kingston, Jamaica
embjm0 = disemb_jm['Embarkation'].value_counts()
embjm0.shape

embjm1 = pd.Series(embjm0[:7])
embjm2 = {'others': sum(embjm0[7:])}
embjm2 = pd.Series(embjm2, index=['others'])
embjm = pd.concat((embjm2, embjm1)).sort_values(ascending=False)

embjm_d = dict(embjm)
embjm_d = {x:y for x, y in embjm_d.items() if y != 0} 
embjm_dkeys, embjm_dvalues = zip(*embjm_d.items())

fig, ax = plt.subplots()
ax.pie(embjm_dvalues, labels=embjm_dkeys, autopct='%1.1f%%', counterclock=False)
plt.show()
    
print(embjm)
    

# Origin disembarked in St. Helena
disemb_hl = file[file.Disembarkation == 'St. Helena']
originhl0 = disemb_hl['Country of Origin'].value_counts()

originhl1 = pd.Series(originhl0[:10])
originhl2 = {'others': sum(originhl0[10:])}
originhl2 = pd.Series(originhl2, index=['others'])
originhl = pd.concat((originhl2, originhl1)).sort_values(ascending=False)

originhl_d = dict(originhl)
originhl_d = {x: y for x, y in originhl_d.items() if y!= 0}
originhl_dkeys, originhl_dvalues = zip(*originhl_d.items())

fig, ax = plt.subplots()
ax.pie(originhl_dvalues, labels=originhl_dkeys, autopct='%1.1f%%')
plt.show()

print(originhl)

#Gênero
sexage_hl = disemb_hl.Sexage.value_counts()
sexagehl_d = dict(sexage_hl)
sexagehl_dkeys, sexagehl_dvalues = zip(*sexagehl_d.items())

fig, ax = plt.subplots()
ax.pie(sexagehl_dvalues, autopct='%1.1f%%')
fig.legend(sexagehl_dkeys, loc=4)
plt.show()

print(sexage_hl)

#Faixa Etária
age_hl = disemb_hl.Age
fig, ax = plt.subplots()    
ax.hist(age_hl, log=True)
ax.set_xlabel('age')
plt.show()

age_hl.describe()

# Frequency of disembarkations at St. Helena
arrivalhl = pd.DataFrame(disemb_hl.Arrival.value_counts()).reset_index(
        ).sort_values(by='index')
arrivalhl = arrivalhl.rename(columns={'index': 'Year', 'Arrival': 
    'Rescued people'})
    
fig, ax = plt.subplots()  
ax.scatter(x='Year', y='Rescued people', data=arrivalhl)  
ax.scatter(x='Year', y='Rescued people', data=arrival, marker='+', 
           c='#D55E00')
ax.set_xlabel('Year')
ax.legend(labels=['St. Helena', 'total'])
plt.show() 

# Embarkations to St. Helena
embhl0 = disemb_hl['Embarkation'].value_counts()

embhl1 = pd.Series(embhl0[:7])
embhl2 = {'others': sum(embhl0[7:])}
embhl2 = pd.Series(embhl2, index=['others'])
embhl = pd.concat((embhl2, embhl1)).sort_values(ascending=False)

embhl_d = dict(embhl)
embhl_d = {x:y for x, y in embhl_d.items() if y != 0} 
embhl_dkeys, embhl_dvalues = zip(*embhl_d.items())

fig, ax = plt.subplots()
ax.pie(embhl_dvalues, labels=embhl_dkeys, autopct='%1.1f%%', counterclock=False)
plt.show()
    
print(embhl)

# all embarkations
fig, ax = plt.subplots()  
ax.scatter(x='Year', y='Rescued people', data=arrivalft)
ax.scatter(x='Year', y='Rescued people', data=arrivalhv)
ax.scatter(x='Year', y='Rescued people', data=arrivalbh)
ax.scatter(x='Year', y='Rescued people', data=arrivaljm)
ax.scatter(x='Year', y='Rescued people', data=arrivalhl)
ax.set_xlabel('Year')
ax.legend(labels=['Freetown', 'Havana', 'Bahamas (unspecified)', 
                   'Kingston, Jamaica', 'St. Helena'], 
loc='upper left', fontsize=9)
plt.show() 

